// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4RRCBLwVjns6KKbrXKG9ZirfYFYv-mVA',
    appId: '1:52881769311:web:53fd1115ce7bd615b3ecea',
    messagingSenderId: '52881769311',
    projectId: 'bookit-99263',
    authDomain: 'bookit-99263.firebaseapp.com',
    storageBucket: 'bookit-99263.appspot.com',
    measurementId: 'G-KZG8G3LTYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS5BSmkFEDHBiWN7rBt_9V3H9ecXp2mjg',
    appId: '1:52881769311:android:ea2154ee1f91c9b1b3ecea',
    messagingSenderId: '52881769311',
    projectId: 'bookit-99263',
    storageBucket: 'bookit-99263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6OPZ2e7u5ZNxHeTyd5FuZk9rLkM7rT8s',
    appId: '1:52881769311:ios:1641562aa28fe473b3ecea',
    messagingSenderId: '52881769311',
    projectId: 'bookit-99263',
    storageBucket: 'bookit-99263.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6OPZ2e7u5ZNxHeTyd5FuZk9rLkM7rT8s',
    appId: '1:52881769311:ios:7df3e90f0bde8a7bb3ecea',
    messagingSenderId: '52881769311',
    projectId: 'bookit-99263',
    storageBucket: 'bookit-99263.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
